// Generated by scripts/generate-product-profile.ts. Do not edit by hand.
export const REQUIRED_RUNTIME_NODE_VERSION = "24.20.0" as const;
export const OFFICIAL_FOUNDATION_PROFILE_SHA256 = "4df823caedbc23df5648a9dfa716bc581716814c4d81ee0223d53dedf6c74b44" as const;
export const BATCH1_CANDIDATE_PROFILE_SHA256 = "42f7ce117d6a08ada8653e2de2e90985c57fb76a94ce2bc20f3a1d5d2cff2fe8" as const;
