// Generated by scripts/generate-product-profile.ts. Do not edit by hand.
export const REQUIRED_RUNTIME_NODE_VERSION = "24.20.0" as const;
export const OFFICIAL_FOUNDATION_PROFILE_SHA256 = "97a3f57185f6a5c163a86322487e62e06f441b8b3b76e163e8517b9409440851" as const;
export const BATCH1_CANDIDATE_PROFILE_SHA256 = "1c9a914b71f348c29849f6e36d1586bdd663ce24ecf108b3284a6c396fd26593" as const;
