// Generated by scripts/generate-product-profile.ts. Do not edit by hand.
export const REQUIRED_RUNTIME_NODE_VERSION = "24.20.0" as const;
export const OFFICIAL_FOUNDATION_PROFILE_SHA256 = "a49b1573fe9e2cf7301f3b8f142c54dc4ea9eb348cd81dce91aaffaac72cfcf3" as const;
export const BATCH1_CANDIDATE_PROFILE_SHA256 = "88c503546eea450c8cddd8e4acbb5eb3d2c3a63db1a92be63575f143c9685214" as const;
